modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Bandit-bytes/too_many_bows/issues"
license = "All Right Reserved"

[[mods]]
modId = "too_many_bows"
version = "${version}"
displayName = "Too Many Bows"
authors = "Bandit-Bytes"
description = '''
An Awesome bow mod that has a lot of unique bows and abilities!
'''
#logoFile = ""

[[dependencies.too_many_bows]]
modId = "neoforge"
type = "required"
versionRange = "[1.21.11-1.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_bows]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.too_many_bows]]
modId = "architectury"
type = "required"
versionRange = "[19.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "too_many_bows.mixins.json"
